apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: cb-admin-ingress-cloud
spec:
  ingressClassName: nginx
  rules:
  - host: cbadmin.vdl.cluster.caemilusa.us
    http:
      paths:
      - backend:
          service:
            name: couchbase-ui
            port:
              number: 8091
        path: /
        pathType: ImplementationSpecific
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: QWRtaW5pc3RyYXRvcg==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/instance: couchbase-operator
  name: auth-couchbase-admin
type: Opaque
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: couchbase
spec:
  backup:
    managed: false 
    image: couchbase/operator-backup:1.3.0 
    serviceAccountName: couchbase-backup 
  image: couchbase/server:7.0.3
  security:
    adminSecret:  auth-couchbase-admin
    rbac:
      managed: true
  buckets:
    managed: false 
  servers:
  - size: 1
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - analytics
    - eventing
    volumeMounts: 
      default: couchbase
  networking:
    adminConsoleServiceTemplate:
      spec:
        type: NodePort
    adminConsoleServices:
      - data
    disableUIOverHTTP: false
    disableUIOverHTTPS: false
    exposeAdminConsole: true
    exposedFeatureServiceTemplate:
      spec:
        type: NodePort
    exposedFeatures:
      - client
      - xdcr
    waitForAddressReachable: 10m0s
    waitForAddressReachableDelay: 2m0s
  volumeClaimTemplates:
  - metadata:
       name: couchbase
    spec:
      storageClassName: hostpath
      resources:
        requests:
          storage: 2Gi
